fn_single_line = true
format_strings = true
hard_tabs = false
max_width = 100
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 8
struct_lit_single_line = true
tab_spaces = 2
trailing_comma = "Never"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true